version: '3'
services: 
  jenkins:
    image: 'jenkins/jenkins:2.60.3'
    # image: 'jenkins/jenkins:2.164.3'
    labels:
      kompose.service.type: nodeport
    user: root
    ports:
      - '8079:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'D:\Programing\jenkins-docker\0-basic:/var/jenkins_config'
volumes:
  jenkins_data:
    driver: local